### ISSUE TITLE
MMM-Pages readme section clarification

### ISSUE THREAD

**Issue by edward-shen** [Bee-Mar/MMM-Simple-Swiper#2]
`excludes` is actually a byproduct of how MMM-pages hides modules:
```js
MM.getModules()
  .exceptWithClass(this.config.excludes)
  .exceptWithClass(this.config.modules[this.curPage])
  .enumerate(module => module.hide(
    self.config.animationTime / 2,
    { lockString: self.identifier }
  ));
```
Since `exceptWithClass` basically acts like a filter, I was thinking of the config option as an exclusion filter, ergo `excludes`. You're right though, the name leaks implementation detail, and it doesn't make much sense for end users. I've changed it to `fixed` (while still supporting `excludes`) to hopefully help people with this. No real action is required by you, unless you want to use `fixed` instead—this issue was just an FYI.

**Comment by Bee-Mar** [comment]
Sounds good! I'll update the README with this information.
