### ISSUE TITLE
I don't think sensors are  safely connected

### ISSUE THREAD

**Issue by kf17** [Bee-Mar/MMM-Simple-Swiper#4]
I performed all steps in correct order without any error but I was only able to swipe once and then the pages were not changing. Sensors are kept 1.5cm apart, and I tried swiping fast and slow but nothing working

I think maybe it is due to improper connection of sensors ? you showed to connect 1k ohm resistor to echo pin but i don't think that's safe for gpio pins, see this tutorial [ModmyPi](https://www.modmypi.com/blog/hc-sr04-ultrasonic-range-sensor-on-the-raspberry-pi)

> Please keep me updated if you find any solution (Thanks in Advance)

**Comment by Bee-Mar** [comment]
I believe you are correct in that they aren't wired the best way, but I haven't experienced any issues with the sensors, and they've been working well for me. I'm curious to know why yours wouldn't be working at all. I've rewired my sensors over the weekend, but haven't had time to test them out. Once everything to be working steadily, I'll post a new diagram.
