### ISSUE TITLE
Won't remain on single page

### ISSUE THREAD

**Issue by jonathancole85** [Bee-Mar/MMM-Simple-Swiper#5]
Jumps around from page to page as though something is moving in front of it. Sprinkled holy water and preformed an exorcism, so good on the ghost. Replaced the sensors with two new ones and the issue remains. Just jumps from page to page.

**Comment by Bee-Mar** [comment]
I'm unsure of where to begin with what might be causing this issue. I'll be updating the version in about two weeks (once I'm done with grad school), which will hopefully resolve any inconsistencies some people are experiencing.

**Comment by jonathancole85** [comment]
Before I close this issue, I will say sorry to have bothered you on this one, turned out it was most likely, P.U.E. possible user error. However, now my issue seems to be that it won't change pages at all, except for when I hit CTRL R. I'm using a brand new Pi 3b, triple checked my wiring this time, new SR04 sensors, new SD, name it, it's new. My configuration is only running clock on screen one and current weather on screen two, for simplicity. I'm stumped.
