### ISSUE TITLE
WiringPi do not works

### ISSUE THREAD

**Issue by csoler11** [Bee-Mar/MMM-Simple-Swiper#8]
hi,
when i was trying to install the module an error get out. When i run "make build-depends" , nodeJS Dependencies install well but Wiring Pi not. In the screen I see this:

```
==========================
Getting WiringPi Dependency
===========================

Cloning to 'wiringPi' ...
fatal: unable to connect to git.drogon.net:
git.drogon.net [0: 188.246.205.22]: errno = Connection refused
git.drogon.net [1: 2a03: 9800: 10: 7b :: 2]: errno = The network is unattainable

/ bin / sh: 6: cd: can not cd to wiringPi
```
What i can do to solution this?
Thanks

**Comment by Bee-Mar** [comment]
Unfortunately, there's nothing I can do about this.  The person responsible for creating `wiringPi` appears to have stopped hosting it. If you try going to `git.drogon.net`, the message "git.drogon.net is temporarily unavailable. Please look for alternatives for wiringPi, etc. -Gordon" Is displayed. This most likely means I'll have to rewrite the module using another library.

**Comment by Bee-Mar** [comment]
See if you can use the version available in the `apt` repo. Try replacing the Makefile you have with this as well.

First run `sudo apt-get install wiringpi`, then delete the contents of the existing Makefile and replace it with the contents below:

`cd` in the home directory of the cloned repo, run `npm install`, then run `make`

```makefile
LDFLAGS=-lpthread -lwiringPi
CFLAGS=-g -o
CC=gcc

swiper: swiper.c
		$(CC) -o swiper swiper.c $(LDFLAGS);\

debug: swiper.c
		$(CC) $(CFLAGS) swiper swiper.c $(LDFLAGS) -DEBUG;

clean:
	rm -rf swiper swiper.o
```

If this doesn't work for you, I'll have to do some experimentation later.

**Comment by csoler11** [comment]
Okey, I will try it tomorrow. Thanks

**Comment by Bee-Mar** [comment]
@csoler11 have you had a chance to try this?

**Comment by csoler11** [comment]
Hi yes i try it and works well. Thanks
Sry not respond before

**Comment by Bee-Mar** [comment]
Cool, I updated the readme to reflect the necessary changes
